# Generated by Django 2.2.6 on 2019-10-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oddaj', '0004_auto_20191016_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='institutiom',
            new_name='institution',
        ),
    ]
